/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sync.View;

import Utils.DataBaseException;
import java.awt.Container;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import sync.Entidade.Funcao;
import sync.Entidade.Funcionario;
import sync.Persistence.DaoFactory;

/**
 *
 * @author eduar
 */
public class TesteDinamico extends JFrame {

    /**
     * Creates new form TesteDinamico
     */
    List<Funcao> funcao;
    public TesteDinamico() {
        initComponents();
        
        try {
            funcao = DaoFactory.newFuncaoDao().readAll();
        } catch (DataBaseException ex) {
            Logger.getLogger(TesteDinamico.class.getName()).log(Level.SEVERE, null, ex);
        }
        initingComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(518, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initingComponents(){

      Container container = this.jPanel1;
      container.setLayout( new GridBagLayout() );
      GridBagConstraints cc = new GridBagConstraints();

      cc.insets = new Insets( 5, 5, 5, 5 );
      cc.gridx = 0; cc.gridy = 0;
      int count = 0;
      
        for (int i = 0; i < 10; i++) {
            
        
      for (Funcao funcao : funcao) {
     
         //construímos um JPanel específico para ele.
         container.add( getFuncaoBox( funcao ), cc);
         cc.gridx++;
         count ++;
          if (count%3==0) {
              cc.gridy++;
              cc.gridx=0;
          }
      }
      }
    }
      private JPanel getFuncaoPanel( Funcao funcao )
   {
      JPanel panel = new JPanel( new GridBagLayout() );
      GridBagConstraints cc = new GridBagConstraints();
//      JLabel label; 
    JCheckBox cBox;

      cc.insets = new Insets( 5, 5, 5, 5 );
      cc.gridx = 0; cc.gridy = 0;
      cBox = new JCheckBox(funcao.getEspecializacao());
//      label = new JLabel( "Aluno: " + funcionario.getNome() );
//      label.setFont( new Font("Tahoma", 1, 16) );
//      panel.add( label, cc );
      panel.add( cBox, cc );

      cc.gridx++;

//      cc.anchor = GridBagConstraints.EAST;
//      label = new JLabel("Valor da Mensalidade:");
//      panel.add( label,  cc);
//
//      cc.gridy++;
//      cc.anchor = GridBagConstraints.WEST;
//      JTextField text = new JTextField( funcionario.getId());
//      panel.add( text, cc );
//
//      cc.gridx++; cc.gridy = 0;
      
      return panel;
   }
      private JCheckBox getFuncaoBox( Funcao funcao )
   {
      JCheckBox box = new JCheckBox( funcao.getEspecializacao() );
      GridBagConstraints cc = new GridBagConstraints();

      
      return box;
      // E assim 'substantivamente', como diria o célebre Seu Madruga.
   }
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesteDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesteDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesteDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesteDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesteDinamico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
